# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Docker在线学习室"
email: me@bingohuang.com
description: > # this means to ignore newlines until "baseurl:"
  你的在线Docker自习室



baseurl: # the subpath of your site, e.g. /blog
url: "http://docker.bingohuang.com" # the base hostname & protocol for your site

#sidebar
default-image: docker-logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: BingoHuang
copyright:
  name: 163yun
  link: 'https://163yun.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1


#social
#facebook: https://www.facebook.com/docker.run
#twitter: https://twitter.com/@docker
github: https://github.com/bingohuang

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/docker.run/
#fb-page-title: Docker

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate]
